# Generated by Django 6.0.1 on 2026-07-26 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='category',
            field=models.CharField(choices=[('CONFERENCE', 'Conference'), ('WORKSHOP', 'Workshop'), ('MEETUP', 'Meetup'), ('HACKATHON', 'Hackathon'), ('WEBINAR', 'Webinar'), ('OTHER', 'Other')], default='OTHER', max_length=20),
        ),
        migrations.AddField(
            model_name='event',
            name='event_type',
            field=models.CharField(choices=[('IN_PERSON', 'In-Person'), ('VIRTUAL', 'Virtual'), ('HYBRID', 'Hybrid')], default='IN_PERSON', max_length=20),
        ),
        migrations.AddField(
            model_name='event',
            name='speaker_name',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='event',
            name='speaker_role',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='registration',
            name='ticket_code',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
    ]
