# Generated by Django 6.0.1 on 2026-07-26 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_event_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
